config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # You can have the root of your site routed with "root"
  root 'topics#preview', as: :topics_preview

  # Session management
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  # HACK for KB
  get 'logout' => 'sessions#destroy'

  # Chat
  resources :chat_sessions, path: 'chat', except: [:index]
  get 'chats' => 'chat_sessions#index', as: :chats
  get 'chats/archived' => 'chat_sessions#archived_list', as: :archived_chats
  patch 'chat/:id/start' => 'chat_sessions#start', as: :start_chat_session
  patch 'chat/:id/end' => 'chat_sessions#end', as: :end_chat_session
  patch 'chat/:id/notes' => 'chat_sessions#update_notes', as: :update_notes_for_chat_session

  # Chat
  get 'private_chats' => 'chat_sessions#index', as: :private_chats
  get 'private_chat/:id' => 'private_chat_sessions#show', as: :private_chat

  patch 'private_chat/:id/end' => 'private_chat_sessions#end', as: :end_private_chat_session
  post 'private_chat/:id/post' => 'private_chat_sessions#post', as: :post_to_private_chat_session

  # Chat messages
  post 'chat/:id/post' => 'chat_sessions#post', as: :post_to_chat_session

  # Topics
  resources :topics, path: 'forum'
  get 'forums/manage' => 'topics#manage', as: :topics_manage
  patch 'forums/manage' => 'topics#update_order'

  # Threads
  resources :topic_threads, path: 'thread'
  get 'threads/hidden' => 'topic_threads#hidden', as: :hidden_threads
  patch 'thread/:id/toggle_pin' => 'topic_threads#toggle_pin', as: :toggle_topic_thread_pin

  # Posts
  get 'post/:id' => 'posts#show', as: :post
  post 'thread/:id/post' => 'posts#new', as: :new_post
  patch 'post/:id/toggle_visibility' => 'posts#toggle_visibility', as: :toggle_post_visibility

  # Users
  get 'users' => 'users#index'
  get 'user/:id' => 'users#show', as: :user
  post 'user/:id/send_password_reset' => 'users#send_password_reset', as: :user_password_reset
  post 'user/:id/hide_activity' => 'users#hide_activity', as: :hide_user_activity
  post 'user/:id/suspend' => 'users#suspend', as: :suspend_user
  post 'user/:id/unsuspend' => 'users#unsuspend', as: :unsuspend_user

  patch 'user/:id/set_access_level' => 'users#set_access_level', as: :set_user_access_level
  patch 'user/:id/set_email' => 'users#set_email', as: :set_user_email
  get 'preferences' => 'preferences#index'
  patch 'preferences' => 'preferences#update'
  patch 'preferences/password' => 'preferences#update_password', as: :update_password

  # New users
  get 'register' => 'users#register', as: :register
  post 'register' => 'users#signup'

  # Password resets
  get 'forgot' => 'password_requests#forgot'
  post 'forgot' => 'password_requests#send_password_reset'
  get 'reset_password/:token' => 'password_requests#reset', as: :password_reset
  post 'reset_password/:token' => 'password_requests#do_reset'

  # Community rules
  get 'community_rules' => 'community_rules#index'

  # resources :notifications
  get "notifications/history" => "notifications#history", as: :notifications_history
  get "notifications/new" => "notifications#new", as: :new_notification
  post "notifications/proof/:content_type" => "notifications#proof", as: :new_notification_proof
  post "notifications/create" => "notifications#create", as: :create_notification

  # API
  scope :api do
    get '' => 'api#index', as: :api
    get 'threads_for_tag/:tag' => 'api#threads_for_tag'
    get 'threads_for_query/:query' => 'api#threads_for_query'
    get 'sessions_for_tag/:tag' => 'api#sessions_for_tag'
    get 'sessions_for_query/:query' => 'api#sessions_for_query'
    get 'user' => 'api#current_user'
    get 'upcoming_chat' => 'api#upcoming_chat'
    get 'forums_overview' => 'api#forums_overview'
  end

  # Admin
  scope :admin do
    get '' => 'landing#admin', as: :admin

    resources :access_levels
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :site
  has_many :topic_threads
  validates :name, presence: true
  validates :site, presence: true

  default_scope { order(:ordinal) }

  scope :visible, -> {
    where(visible: true)
  }

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  layout 'modal', except: ['preview', 'show']

  # Public

  def preview
    @topics = @site.topics
  end

  def show
    @topic = @site.topics.find(params[:id])

    # Restrict access to hidden topics
    unless @topic.visible?
      unless current_user_can?(:topics_viewHidden)
        raise Exceptions::NotFoundError
      end
    end

    @threads = @topic.topic_threads.where(public: true).paginate(:page => params[:page])
  end

  # Admin

  def manage
    require_permission :forums_modify
    @topics = @site.topics
  end

  def update_order
    require_permission :forums_modify

    params[:topics_visible] ||= {}

    params[:topics_order].each_with_index do |topic_id, index|
      visible = params[:topics_visible][topic_id].present?
      @site.topics.find(topic_id.to_i).update(ordinal: index, visible: visible)
    end

    flash[:success] = "Forums successfully updated"
    redirect_to topics_preview_path

    params[:topics_order].inspect
  end

  def new
    require_permission :topics_modify
    @topic = @site.topics.new
  end

  def create
    require_permission :topics_modify
    @topic = @site.topics.new(topic_params)

    if @topic.save
      flash[:success] = "#{@topic.name} successfully created"
      redirect_to topics_preview_path
    else
      flash.now[:error] = @topic.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    require_permission :topics_modify
    @topic = @site.topics.find(params[:id])

    render :edit
  end

  def update
    require_permission :topics_modify
    @topic = @site.topics.find(params[:id])

    if @topic.update(topic_params)
      flash[:success] = "#{@topic.name} successfully updated"
      redirect_to topic_path(@topic)
    else
      flash.now[:error] = @topic.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description)
  end
end

app/views/topics/_form.html.slim
= form_for @topic do |f|
  .label
    .label__title 
      | Title of forum
      span.alert *
    .form__textfield
        = f.text_field :name, placeholder:"Enter forum title", class:"input__textfield"

  .label
    .label__title
      | Forum description
      span.alert *
    .form__textarea.js-textarea
        = f.text_area :description, placeholder:"Enter forum description", class:"input__textarea js-free-text"

  .form__button.js-popup-close Cancel
  button.form__button.primary Save

  .label
    .message-required
      | Required fields (
      span.alert *
      | )

app/views/topics/edit.html.slim
h1 Edit Forum

= render 'form'

app/views/topics/manage.html.slim
h1 Manage forums

= form_tag topics_manage_path, method: :patch do |f|
  .label
    .label__title
      | Forums overview
      span.alert *
    .form__textarea.js-textarea
      = text_area_tag 'description', "Enter forums overview description", class:"input__textarea js-free-text"

  .label
    .edit__forums-titles
      .label__title Forums
      .label__title Show

    ol.edit__forums-list.js-topics-reorder
      - @topics.each do |topic|
        li.edit__forums-row
          .topic__title = topic.name
          input type="hidden" name="topics_order[]" value=topic.id
          label.checkbox
            = insert_svg("icons/icon_reorder.svg", class:'icon__reorder')
            = check_box_tag "topics_visible[#{topic.id}]", 1, topic.visible, class:"input__checkbox"
            .form__checkbox

  .form__button.js-popup-close Cancel
  button.form__button.primary Save

app/views/topics/new.html.slim
h1 New Forum

= render 'form'

app/views/topics/preview.html.slim
- content_for :dark_strip do
  .strip__dark-forum
    h1 Forums

- if current_user_can?(:forums_modify)
  - content_for :edit_strip do
    a.btn__edit href=topics_manage_path data-modal=true Manage forums

- content_for :light_strip do
  p.js-forums_overview

- content_for :sidebar_locked do
  = render 'partials/sidebar', expanded: true

- @topics.each do |topic|
  - if current_user_can?(:topics_viewHidden) || topic.visible?
    .topic__preview data-hidden=!(topic.visible?)
      .topic__name
        h2
          a href=topic_path(topic) = topic.name
          - if !topic.visible?
            span
              | (Hidden forum)

      .topicThreads
        = render topic.topic_threads.preview

      .topic__viewMore
        a href=topic_path(topic) View more on this forum

app/views/topics/show.html.slim
- content_for :dark_strip do
  .strip__dark-topic
    - unless @topic.visible
      .strip__modOnly Hidden Forum. Only visible to moderators.
    h2
      a href=topics_preview_path 
        = insert_svg("icons/icon_back-arrow-white.svg", class:"icon__back")
        | Forums
    h1
      =< @topic.name

- if current_user_can?(:topics_modify)
  - content_for :edit_strip do
    a.btn__edit href=edit_topic_path(@topic) data-modal=true Edit details

- content_for :light_strip do
  p = @topic.description

- content_for :sidebar do
  = render 'partials/sidebar'

.threads
  - if @threads.any?
    = render @threads
    = render 'partials/pagination', paginated: @threads
  - else
    .message-noThreads
      = insert_svg("empty-avatar.svg", class:"icon__avatar")
      | There's nothing here! Be the first to create a new thread.