config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # You can have the root of your site routed with "root"
  root 'topics#preview', as: :topics_preview

  # Session management
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  # HACK for KB
  get 'logout' => 'sessions#destroy'

  # Chat
  resources :chat_sessions, path: 'chat', except: [:index]
  get 'chats' => 'chat_sessions#index', as: :chats
  get 'chats/archived' => 'chat_sessions#archived_list', as: :archived_chats
  patch 'chat/:id/start' => 'chat_sessions#start', as: :start_chat_session
  patch 'chat/:id/end' => 'chat_sessions#end', as: :end_chat_session
  patch 'chat/:id/notes' => 'chat_sessions#update_notes', as: :update_notes_for_chat_session

  # Chat
  get 'private_chats' => 'chat_sessions#index', as: :private_chats
  get 'private_chat/:id' => 'private_chat_sessions#show', as: :private_chat

  patch 'private_chat/:id/end' => 'private_chat_sessions#end', as: :end_private_chat_session
  post 'private_chat/:id/post' => 'private_chat_sessions#post', as: :post_to_private_chat_session

  # Chat messages
  post 'chat/:id/post' => 'chat_sessions#post', as: :post_to_chat_session

  # Topics
  resources :topics, path: 'forum'
  get 'forums/manage' => 'topics#manage', as: :topics_manage
  patch 'forums/manage' => 'topics#update_order'

  # Threads
  resources :topic_threads, path: 'thread'
  get 'threads/hidden' => 'topic_threads#hidden', as: :hidden_threads
  patch 'thread/:id/toggle_pin' => 'topic_threads#toggle_pin', as: :toggle_topic_thread_pin

  # Posts
  get 'post/:id' => 'posts#show', as: :post
  post 'thread/:id/post' => 'posts#new', as: :new_post
  patch 'post/:id/toggle_visibility' => 'posts#toggle_visibility', as: :toggle_post_visibility

  # Users
  get 'users' => 'users#index'
  get 'user/:id' => 'users#show', as: :user
  post 'user/:id/send_password_reset' => 'users#send_password_reset', as: :user_password_reset
  post 'user/:id/hide_activity' => 'users#hide_activity', as: :hide_user_activity
  post 'user/:id/suspend' => 'users#suspend', as: :suspend_user
  post 'user/:id/unsuspend' => 'users#unsuspend', as: :unsuspend_user

  patch 'user/:id/set_access_level' => 'users#set_access_level', as: :set_user_access_level
  patch 'user/:id/set_email' => 'users#set_email', as: :set_user_email
  get 'preferences' => 'preferences#index'
  patch 'preferences' => 'preferences#update'
  patch 'preferences/password' => 'preferences#update_password', as: :update_password

  # New users
  get 'register' => 'users#register', as: :register
  post 'register' => 'users#signup'

  # Password resets
  get 'forgot' => 'password_requests#forgot'
  post 'forgot' => 'password_requests#send_password_reset'
  get 'reset_password/:token' => 'password_requests#reset', as: :password_reset
  post 'reset_password/:token' => 'password_requests#do_reset'

  # Community rules
  get 'community_rules' => 'community_rules#index'

  # resources :notifications
  get "notifications/history" => "notifications#history", as: :notifications_history
  get "notifications/new" => "notifications#new", as: :new_notification
  post "notifications/proof/:content_type" => "notifications#proof", as: :new_notification_proof
  post "notifications/create" => "notifications#create", as: :create_notification

  # API
  scope :api do
    get '' => 'api#index', as: :api
    get 'threads_for_tag/:tag' => 'api#threads_for_tag'
    get 'threads_for_query/:query' => 'api#threads_for_query'
    get 'sessions_for_tag/:tag' => 'api#sessions_for_tag'
    get 'sessions_for_query/:query' => 'api#sessions_for_query'
    get 'user' => 'api#current_user'
    get 'upcoming_chat' => 'api#upcoming_chat'
    get 'forums_overview' => 'api#forums_overview'
  end

  # Admin
  scope :admin do
    get '' => 'landing#admin', as: :admin

    resources :access_levels
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include ApplicationHelper

  belongs_to :user
  validates :user, presence: true

  enum status: [
    :sending,
    :sent
  ]

  default_scope { order(created_at: :desc) }

  def site
    user.site
  end

  def self.content_types
    [
      :scheduled_chat_content,
      :today_chat_content,
      :new_article_content
    ]
  end

  def self.scheduled_chat_content(site, options = {})
    chat_session = ChatSession.find_by(id: options[:chat_session_id]) || ChatSession.new(
      discreet_name: '<discreet name>',
      scheduled_for: Time.now
    )

    link = chat_session.id ? ShortenedUrl.shorten(chat_session.public_path) : "<link>"

    %{
      There's a live chat about #{chat_session.discreet_name} that might
      interest you on #{chat_session.scheduled_for_date} at
      #{chat_session.scheduled_for_time}. To find out more: #{link}
    }.gsub(/\s+/, " ")
  end

  def self.today_chat_content(site, options = {})
    chat_session = ChatSession.find_by(id: options[:chat_session_id]) || ChatSession.new(
      discreet_name: '<discreet name>',
      scheduled_for: Time.now
    )

    link = chat_session.id ? ShortenedUrl.shorten(chat_session.public_path) : "<link>"

    %{
      Today's live chat discussion about #{chat_session.discreet_name}
      will begin at at #{chat_session.scheduled_for_time}.
      To find out more: #{link}
    }.gsub(/\s+/, " ")
  end

  def self.new_article_content(site, options = {})
    if options[:article_data]
      article_url, discreet_subject = options[:article_data].split("|", 2)
      article_link = ShortenedUrl.shorten(article_url)
    else
      discreet_subject = "<discreet description>"
      article_link = "$link"
    end

    %{
      There's a new article that might interest you.
      View it here: #{article_link}
    }.gsub(/\s+/, " ")
  end

  def self.subject_title_for_data(data)
    if data[:article_data]
      data[:article_data].split("|", 2)[1]
    elsif data[:chat_session_id]
      ChatSession.find_by(id: data[:chat_session_id]).try(&:name)
    end
  end

  def dispatch(host)
    # Only run on unsent messages
    return if sent?

    # Email notification
    site.users.where(email_opted_in: true).each do |user|
      UserMailer.notification(
        host,
        user,
        content
      ).deliver_now
      update(email_count: email_count + 1)
    end

    # SMS notifications
    numbers = site.users.where(sms_opted_in: true).pluck(:sms_contact)

    # Remove any non-numeric chars
    to_numbers = numbers.map{|n| n.tr("^0-9", "") }.join(",")
    escaped_content = ERB::Util.url_encode(content)

    sms_api_url = [
      "https://api.smsbroadcast.com.au/api-adv.php?",
      "username=#{Rails.configuration.smsbroadcast_username}&",
      "password=#{ERB::Util.url_encode(Rails.configuration.smsbroadcast_password)}&",
      "to=#{to_numbers}&",
      "from=#{site.pretty_name}&",
      "message=#{escaped_content}&",
      "maxsplit=3"
    ].join()

    open(sms_api_url).read
    update(sms_count: numbers.count)

    # Twitter notification
    credentials = Rails.configuration.twitter_credentials[site.name]
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = credentials[:consumer_key]
      config.consumer_secret = credentials[:consumer_secret]
      config.access_token = credentials[:access_token]
      config.access_token_secret = credentials[:access_token_secret]
    end

    site.users.where(twitter_opted_in: true).each do |user|
      client.create_direct_message(user.twitter_contact, content)
      update(twitter_count: twitter_count + 1)
    end

    # Update status
    update(status: :sent)
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  include ApplicationHelper
  layout 'modal', except: ['history']

  def history
    require_permission :notification_create
    @notifications = @site.notifications
  end

  def new
    require_permission :notification_create

    @chat_sessions = @site.chat_sessions.where(status: [ChatSession.statuses['open'], ChatSession.statuses['scheduled']])
    @articles = fetch_articles
  end

  def proof
    require_permission :notification_create

    @content_type = params.permit(:content_type)[:content_type].to_sym
    raise Exceptions::NotFoundError unless Notification.content_types.include?(@content_type)

    @notification_data = notification_params[:data]
    @subject_title = Notification.subject_title_for_data(@notification_data)
    @notification_content = Notification.send(@content_type, *[@site, @notification_data])
  end

  def create
    require_permission :notification_create

    @content_type = notification_params[:content_type].to_sym
    raise Exceptions::NotFoundError unless Notification.content_types.include?(@content_type)

    @notification_data = notification_params[:data]

    @notification_content = Notification.send(@content_type, *[@site, @notification_data])
    @subject_title = Notification.subject_title_for_data(@notification_data)

    @notification = @current_user.notifications.create(
      content: @notification_content,
      content_type: @content_type,
      subject_title: @subject_title
    )

    @notification.dispatch(@host)

    flash[:success] = "Notification has been created"
    redirect_to notifications_history_path
  end

  private

  def fetch_articles
    api_url = link_to_kb("api")
    api_raw = open(api_url).read
    api_data = JSON.parse(api_raw)
    api_data["articles"]
  end

  def notification_params
    params.require(:notification).permit(:content_type, data: [:chat_session_id])
  end

end

app/views/notifications/history.html.slim
- content_for :custom_title do
  title = "Notification History · #{@site.name.capitalize}"

- content_for :chat_strip do
  .strip__dark-regular
    .strip__modOnly Only visible to moderators
    h1 Notification history

- content_for :sidebar do
  = render 'partials/sidebar'

.archiveList
  - @notifications.each do |notification|

    .notificationHistory
      .text__main
        h3 = notification.subject_title || "(Unknown title)"
        - notification_type = nil
        - if notification.content_type == 'scheduled_chat_content'
          - notification_type = "New scheduled chat"
        - elsif notification.content_type == 'today_chat_content'
          - notification_type = "Upcoming chat today"
        - elsif notification.content_type == 'new_article_content'
          - notification_type = "New article"

        p
          strong Notification type: 
          = notification_type || "(Unknown type)"
        p
          strong Message: 
          = notification.content

      .text__sub
        p
          strong Sent by: 
          = notification.user.name

        p
          strong Sent at: 
          = notification.created_at.strftime("%l.%M%p, ").downcase + notification.created_at.strftime("%e %B, %Y")

        p
          strong Status: 
          = notification.status.humanize

        p
          strong Total emails: 
          = notification.email_count

        p
          strong Total SMS: 
          = notification.sms_count

        p
          strong Total Twitter direct messages: 
          = notification.twitter_count

app/views/notifications/new.html.slim
h1 Send notification

= form_tag new_notification_proof_path(:scheduled_chat_content) do |f|
  
  .label
    .label__title New scheduled chat notification
    .label__desc Select the chat you'd like to send a notification for.

  .label
    = render 'components/dropdown',
      name: "notification[data][chat_session_id]",
      id: "notification[data][chat_session_id]",
      options: Hash[@chat_sessions.pluck(:id, :name)]

  .label.large
    button.form__button.meta.primary Proof and send

= form_tag new_notification_proof_path(:today_chat_content) do |f|
  
  .label
    .label__title Upcoming chat today notification
    .label__desc Select the chat you'd like to send a notification for.

  .label
    = render 'components/dropdown',
      name: "notification[data][chat_session_id]",
      id: "notification[data][chat_session_id]",
      options: Hash[@chat_sessions.pluck(:id, :name)]

  .label.large
    button.form__button.meta.primary Proof and send

= form_tag new_notification_proof_path(:new_article_content) do |f|
  
  .label
    .label__title New article notification
    .label__desc Select the article you'd like to send a notification for.

  .label
    = render 'components/dropdown',
      name: "notification[data][article_data]",
      id: "notification[data][article_data]",
      options: Hash[@articles.map{|article| [article.join('|'), article[1]]}]

  .label.large
    button.form__button.meta.primary Proof and send

app/views/notifications/proof.html.slim
h1 Proof notification

= form_tag create_notification_path do

  input type="hidden" name="notification[content_type]" value=@content_type
  - @notification_data.each do |k, v|
    input type="hidden" name="notification[data][#{k}]" value=v

  .label
    .label__title Notification for:
    .label__desc = @subject_title

  .label.small
    .label__title Preview:
  .label.small
    .bubble = @notification_content

  .label.med
    .label__title Total notifications:
    .label__desc
      | Email: 
      = @site.users.where(email_opted_in: true).count
    .label__desc
      | SMS: 
      = @site.users.where(sms_opted_in: true).count
    .label__desc
      | Twitter DM: 
      = @site.users.where(twitter_opted_in: true).count

  .label.large
    .message-modal
      h3 Please note:
      ul
        li = "This may take a few moments, do not refresh your browser."

  .form__button.js-popup-close Cancel
  button.form__button.primary Send