config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # You can have the root of your site routed with "root"
  root 'topics#preview', as: :topics_preview

  # Session management
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  # HACK for KB
  get 'logout' => 'sessions#destroy'

  # Chat
  resources :chat_sessions, path: 'chat', except: [:index]
  get 'chats' => 'chat_sessions#index', as: :chats
  get 'chats/archived' => 'chat_sessions#archived_list', as: :archived_chats
  patch 'chat/:id/start' => 'chat_sessions#start', as: :start_chat_session
  patch 'chat/:id/end' => 'chat_sessions#end', as: :end_chat_session
  patch 'chat/:id/notes' => 'chat_sessions#update_notes', as: :update_notes_for_chat_session

  # Chat
  get 'private_chats' => 'chat_sessions#index', as: :private_chats
  get 'private_chat/:id' => 'private_chat_sessions#show', as: :private_chat

  patch 'private_chat/:id/end' => 'private_chat_sessions#end', as: :end_private_chat_session
  post 'private_chat/:id/post' => 'private_chat_sessions#post', as: :post_to_private_chat_session

  # Chat messages
  post 'chat/:id/post' => 'chat_sessions#post', as: :post_to_chat_session

  # Topics
  resources :topics, path: 'forum'
  get 'forums/manage' => 'topics#manage', as: :topics_manage
  patch 'forums/manage' => 'topics#update_order'

  # Threads
  resources :topic_threads, path: 'thread'
  get 'threads/hidden' => 'topic_threads#hidden', as: :hidden_threads
  patch 'thread/:id/toggle_pin' => 'topic_threads#toggle_pin', as: :toggle_topic_thread_pin

  # Posts
  get 'post/:id' => 'posts#show', as: :post
  post 'thread/:id/post' => 'posts#new', as: :new_post
  patch 'post/:id/toggle_visibility' => 'posts#toggle_visibility', as: :toggle_post_visibility

  # Users
  get 'users' => 'users#index'
  get 'user/:id' => 'users#show', as: :user
  post 'user/:id/send_password_reset' => 'users#send_password_reset', as: :user_password_reset
  post 'user/:id/hide_activity' => 'users#hide_activity', as: :hide_user_activity
  post 'user/:id/suspend' => 'users#suspend', as: :suspend_user
  post 'user/:id/unsuspend' => 'users#unsuspend', as: :unsuspend_user

  patch 'user/:id/set_access_level' => 'users#set_access_level', as: :set_user_access_level
  patch 'user/:id/set_email' => 'users#set_email', as: :set_user_email
  get 'preferences' => 'preferences#index'
  patch 'preferences' => 'preferences#update'
  patch 'preferences/password' => 'preferences#update_password', as: :update_password

  # New users
  get 'register' => 'users#register', as: :register
  post 'register' => 'users#signup'

  # Password resets
  get 'forgot' => 'password_requests#forgot'
  post 'forgot' => 'password_requests#send_password_reset'
  get 'reset_password/:token' => 'password_requests#reset', as: :password_reset
  post 'reset_password/:token' => 'password_requests#do_reset'

  # Community rules
  get 'community_rules' => 'community_rules#index'

  # resources :notifications
  get "notifications/history" => "notifications#history", as: :notifications_history
  get "notifications/new" => "notifications#new", as: :new_notification
  post "notifications/proof/:content_type" => "notifications#proof", as: :new_notification_proof
  post "notifications/create" => "notifications#create", as: :create_notification

  # API
  scope :api do
    get '' => 'api#index', as: :api
    get 'threads_for_tag/:tag' => 'api#threads_for_tag'
    get 'threads_for_query/:query' => 'api#threads_for_query'
    get 'sessions_for_tag/:tag' => 'api#sessions_for_tag'
    get 'sessions_for_query/:query' => 'api#sessions_for_query'
    get 'user' => 'api#current_user'
    get 'upcoming_chat' => 'api#upcoming_chat'
    get 'forums_overview' => 'api#forums_overview'
  end

  # Admin
  scope :admin do
    get '' => 'landing#admin', as: :admin

    resources :access_levels
  end
end

app/models/password_request.rb
class PasswordRequest < ApplicationRecord
  belongs_to :user

  before_validation :assign_token

  private

  def assign_token
    self.token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/password_requests_controller.rb
class PasswordRequestsController < ApplicationController
  layout 'modal'

  def send_password_reset
    # Attempt to find user(s) by name, or failing that by email address
    # Whilst usernames are enforced unique, emails are not,
    # so where is used rather than find, with results then iterated over
    users = @site.users.where(name: params[:user][:name])
    if users.empty?
      users = @site.users.where(email: params[:user][:name])
    end

    users.each do |user|
      unless user.email.blank?
        # Only send email to users with an email address,
        # but pretend it was sent regardless to not leak
        # information about accounts
        user.send_password_reset(@host)
      end
    end

    render :reset_sent
  end

  def reset
    @password_request = @site.password_requests.find_by(token: params[:token])
    require_existence @password_request
  end

  def do_reset
    @password_request = @site.password_requests.find_by(token: params[:token])
    require_existence @password_request

    user = @password_request.user

    if user.update(password_reset_params)
      # Remove all pending requests
      user.password_requests.destroy_all

      # Log user in
      log_in(user)
      flash[:success] = "Password reset successfully. Welcome back, #{user.name}"
      redirect_to topics_preview_path
    else
      flash.now[:error] = user.errors.full_messages.to_sentence
      render :reset
    end

  end

  private

  def password_reset_params
    params.require(:user).permit(
      :password,
      :password_confirmation
    )
  end

end

app/views/password_requests/forgot.html.slim
.modal__small
  h2 Lost Password

  = form_for(:user, url: forgot_path) do |f|
    .label.med
      .label__desc Username or email
      .form__textfield
        = f.text_field :name, class:"input__textfield", placeholder:"Enter username"

    .label
      .message-modal
        h3 Please note:
        ul
          li = "Only users with email addresses can reset their account"

    .label
      button.form__button.primary.fullwidth Send reset email

    .label
      a.label__link href=login_path data-modal=true Back to Log in

app/views/password_requests/reset.html.slim
.modal__small
  h2 Reset password

  = form_for(:user, url: password_reset_path(@password_request.token)) do |f|
    .label
      .label__desc
        | Password
        span.alert *
      .form__textfield
        = f.password_field :password, class:"input__textfield", placeholder:"Enter password"

    .label.large
      .label__desc
        | Password confirmation
        span.alert *
      .form__textfield
        = f.password_field :password_confirmation, class:"input__textfield", placeholder:"Re-enter password"

    button.form__button.fullwidth Reset

    .label
      .message-required
        | Required fields (
        span.alert *
        | )

app/views/password_requests/reset_sent.html.slim
.modal__small
  h2 Lost Password

  .label.med
    .label__desc An email with reset information has been sent.

  .label
    .message-modal
      h3 Please note:
      ul
        li = "If you do not receive an email, the username or email address you have provided is either not registered or incorrect. Please try again."

  .label.large
    a.label__link href=topics_preview_path Back to Forums